angular.module('inspctr.constants', [])
.constant('apiUrl', '@apiUrl@')
.constant('placeholderImage', '@placeholderImage@')
.constant('placeholderImagePath', '@placeholderImagePath@')
.constant('mapboxDefaultSecretToken', '@mapboxDefaultSecretToken@')
.constant('mapboxAccessToken', '@mapboxAccessToken@')
.constant('mapboxMapId', '@mapboxMapId@')
.constant("qimgUrl", "@qimgUrl@")
.constant("qimgToken", "@qimgToken@")
.constant("cameraFunctionalityAvailable", "@cameraFunctionalityAvailable@")
;